on: 
    push:
        branches:
            - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4    
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.ftp_user }}
        server: ${{ secrets.ftp_host }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local_path: './index.html'
        remote_path: './node_apps/'
        sftpArgs: '-o ConnectTimeout=10'
        sftp_only: true